/**

* BOLEIROS DE CRISTO
* Lista fixa de jogadores
  */

const jogadoresFixos = [
{ nome: "Adeilson", categoria: 4.0, goleiro: false },
{ nome: "Adriel", categoria: 3.0, goleiro: false },
{ nome: "Adryel", categoria: 4.0, goleiro: false },
{ nome: "Alex", categoria: 3.0, goleiro: false },
{ nome: "Alexsander jr", categoria: 2.5, goleiro: false },
{ nome: "Andrew", categoria: 3.0, goleiro: false },
{ nome: "André", categoria: 3.0, goleiro: false },
{ nome: "Araújo", categoria: 4.0, goleiro: false },
{ nome: "Arthur", categoria: 3.0, goleiro: false },
{ nome: "Arthur Manoel", categoria: 2.0, goleiro: false },
{ nome: "Azevedo", categoria: 4.0, goleiro: false },
{ nome: "Beto", categoria: 4.0, goleiro: false },
{ nome: "Breno Beto", categoria: 3.0, goleiro: false },
{ nome: "Caio", categoria: 3.0, goleiro: false },
{ nome: "Carlos", categoria: 4.0, goleiro: false },
{ nome: "Carlos Heraldo", categoria: 3.0, goleiro: false },
{ nome: "Daniel Gomes", categoria: 3.0, goleiro: false },
{ nome: "Davi", categoria: 1.0, goleiro: false },
{ nome: "Davi Serra", categoria: 4.0, goleiro: false },
{ nome: "Douglas", categoria: 2.0, goleiro: false },
{ nome: "Eduardo", categoria: 4.0, goleiro: false },
{ nome: "Erick", categoria: 4.0, goleiro: false },
{ nome: "Erick Nunes", categoria: 3.0, goleiro: true },
{ nome: "Felipe", categoria: 4.0, goleiro: false },
{ nome: "Felipe Gomes", categoria: 3.0, goleiro: false },
{ nome: "Felipe Oliveira", categoria: 3.0, goleiro: true },
{ nome: "Fernando (Jr.)", categoria: 3.0, goleiro: false },
{ nome: "Fernando Carlim", categoria: 3.0, goleiro: false },
{ nome: "Fernando Jr.", categoria: 3.0, goleiro: false },
{ nome: "Filipi", categoria: 2.0, goleiro: false },
{ nome: "Frank", categoria: 2.0, goleiro: true },
{ nome: "Gabriel", categoria: 4.0, goleiro: false },
{ nome: "Gabriel Beto", categoria: 3.0, goleiro: false },
{ nome: "Gabriel Hot", categoria: 4.0, goleiro: false },
{ nome: "Gilmar", categoria: 3.0, goleiro: false },
{ nome: "Giovani", categoria: 3.0, goleiro: false },
{ nome: "Guilherme", categoria: 4.0, goleiro: false },
{ nome: "Guilherme Beto", categoria: 4.0, goleiro: false },
{ nome: "Gustavo", categoria: 4.0, goleiro: false },
{ nome: "Heber", categoria: 4.0, goleiro: false },
{ nome: "Heraldo", categoria: 3.0, goleiro: false },
{ nome: "Hugo", categoria: 2.0, goleiro: false },
{ nome: "Hugo Correia", categoria: 3.0, goleiro: false },
{ nome: "Hyuri", categoria: 3.0, goleiro: false },
{ nome: "Igor", categoria: 4.0, goleiro: false },
{ nome: "Jonas", categoria: 3.0, goleiro: false },
{ nome: "Jordan", categoria: 3.0, goleiro: true },
{ nome: "João Gabriel", categoria: 2.0, goleiro: false },
{ nome: "João Nóvoa", categoria: 3.0, goleiro: false },
{ nome: "João Pedro", categoria: 3.0, goleiro: false },
{ nome: "João Poubel", categoria: 1.0, goleiro: false },
{ nome: "João Roberto", categoria: 3.0, goleiro: false },
{ nome: "Júnior", categoria: 3.0, goleiro: false },
{ nome: "Kaio Couto", categoria: 3.0, goleiro: false },
{ nome: "Karina", categoria: 1.0, goleiro: false },
{ nome: "Leandro", categoria: 5.0, goleiro: false },
{ nome: "Leo Muniz", categoria: 3.0, goleiro: false },
{ nome: "Leonardo", categoria: 4.0, goleiro: false },
{ nome: "Levir", categoria: 4.0, goleiro: false },
{ nome: "Lorena", categoria: 1.0, goleiro: false },
{ nome: "Loureiro", categoria: 3.0, goleiro: true },
{ nome: "Lucas Ferreira Conv.", categoria: 3.0, goleiro: false },
{ nome: "Lucas Gabigol", categoria: 4.0, goleiro: false },
{ nome: "Lucas Matheus", categoria: 3.0, goleiro: false },
{ nome: "Lucas Motta", categoria: 3.0, goleiro: false },
{ nome: "Lucas Pereira", categoria: 3.0, goleiro: false },
{ nome: "Lucas Pilão", categoria: 3.0, goleiro: false },
{ nome: "Luis Araújo", categoria: 4.0, goleiro: false },
{ nome: "Luis Felipe", categoria: 4.0, goleiro: false },
{ nome: "Luis Paulo", categoria: 4.0, goleiro: false },
{ nome: "Luiz Guilherme", categoria: 3.0, goleiro: false },
{ nome: "Luy", categoria: 4.0, goleiro: false },
{ nome: "Macena", categoria: 3.0, goleiro: false },
{ nome: "Maicão", categoria: 3.0, goleiro: false },
{ nome: "Marcos Aurélio", categoria: 3.0, goleiro: false },
{ nome: "Marquinhos", categoria: 3.0, goleiro: false },
{ nome: "Matheus", categoria: 4.0, goleiro: false },
{ nome: "Matheus Coelho", categoria: 3.0, goleiro: false },
{ nome: "Matheus Conv", categoria: 3.0, goleiro: false },
{ nome: "Matheus Hot", categoria: 2.0, goleiro: false },
{ nome: "Matheus Nunes", categoria: 3.5, goleiro: false },
{ nome: "Matheus Sales", categoria: 3.0, goleiro: false },
{ nome: "Miguel", categoria: 2.0, goleiro: false },
{ nome: "Moraes", categoria: 4.0, goleiro: false },
{ nome: "Moreno", categoria: 3.0, goleiro: false },
{ nome: "Nicholas", categoria: 4.0, goleiro: false },
{ nome: "Nogueira", categoria: 4.0, goleiro: false },
{ nome: "Osni", categoria: 4.0, goleiro: false },
{ nome: "Pablo", categoria: 3.0, goleiro: false },
{ nome: "Paulinho", categoria: 2.0, goleiro: true },
{ nome: "Paulo M.", categoria: 4.0, goleiro: false },
{ nome: "PC", categoria: 4.0, goleiro: false },
{ nome: "Pedrinho", categoria: 3.0, goleiro: false },
{ nome: "Pedro", categoria: 3.0, goleiro: false },
{ nome: "Pedro L", categoria: 4.0, goleiro: false },
{ nome: "Pedro Paulo", categoria: 2.0, goleiro: false },
{ nome: "Popó", categoria: 3.5, goleiro: false },
{ nome: "Rafael", categoria: 2.0, goleiro: false },
{ nome: "Rafael Santos", categoria: 3.0, goleiro: false },
{ nome: "Renan", categoria: 3.0, goleiro: false },
{ nome: "Renan Amorim", categoria: 2.0, goleiro: false },
{ nome: "Rhian", categoria: 3.0, goleiro: false },
{ nome: "Rhuann", categoria: 3.0, goleiro: false },
{ nome: "Ricardo", categoria: 3.0, goleiro: false },
{ nome: "Ricardo T.", categoria: 4.0, goleiro: false },
{ nome: "Rodrigo", categoria: 4.0, goleiro: false },
{ nome: "Romulo", categoria: 3.0, goleiro: false },
{ nome: "Ruan", categoria: 4.0, goleiro: false },
{ nome: "Russo", categoria: 4.0, goleiro: false },
{ nome: "Samuel Convidado", categoria: 4.0, goleiro: false },
{ nome: "Samuel Freire", categoria: 2.0, goleiro: false },
{ nome: "Thamires", categoria: 1.0, goleiro: false, menina: true },
{ nome: "Thamyris", categoria: 1.0, goleiro: false, menina: true },
{ nome: "Tio Alexandre", categoria: 3.0, goleiro: false },
{ nome: "Vieira", categoria: 3.0, goleiro: false },
{ nome: "Vini", categoria: 3.0, goleiro: false },
{ nome: "Vinicius Henriques", categoria: 4.0, goleiro: false },
{ nome: "Wagner", categoria: 4.5, goleiro: false },
{ nome: "Walace", categoria: 4.0, goleiro: false },
{ nome: "Wanderlei", categoria: 1.0, goleiro: false },
{ nome: "Washington", categoria: 3.0, goleiro: false },
{ nome: "Wellington", categoria: 3.0, goleiro: false },
{ nome: "Windsor", categoria: 3.0, goleiro: false },
{ nome: "Yan", categoria: 3.0, goleiro: false },
{ nome: "Yan Goleiro", categoria: 3.0, goleiro: true },
{ nome: "Yuri Felipe", categoria: 4.0, goleiro: false }
];
